name: ChatPerms
main: ChatPerms\Main
version: 1.2.0
api: 5.0.0
description: A plugin that manages chat permissions and formats
author: MilkAndCookiz

commands:
  cp:
    description: ChatPerms main command
    permission: chatperms.command
    aliases: [chatperms]

permissions:
  chatperms.command:
    description: Basic command access
    default: op
  
  chatperms.command.setgroup:
    description: Set a player's group
    default: op
  
  chatperms.command.creategroup:
    description: Create a new group
    default: op
  
  chatperms.command.removegroup:
    description: Remove a group
    default: op
  
  chatperms.command.addgroupperm:
    description: Add permission to a group
    default: op
  
  chatperms.command.removegroupperm:
    description: Remove permission from a group
    default: op
  
  chatperms.command.listgroups:
    description: List all groups
    default: op
  
  chatperms.command.checkplayer:
    description: Check a player's permissions
    default: op
  
  chatperms.command.mute:
    description: Mute a player
    default: op
  
  chatperms.command.unmute:
    description: Unmute a player
    default: op
  
  chatperms.command.mutelist:
    description: List all muted players
    default: op
  
  chatperms.command.stats:
    description: View chat statistics
    default: op
  
  chatperms.command.tempgroup:
    description: Assign temporary groups to players
    default: op
  
  chatperms.command.tempgroupcheck:
    description: Check temporary group status
    default: op
  
  chatperms.group.default:
    description: Default group permission
    default: true
  
  chatperms.group.vip:
    description: VIP group permission
    default: false
  
  chatperms.group.admin:
    description: Admin group permission
    default: op